export const types = {
  mutations: {
    SET_POST_CURRENT: "SET_POST_CURRENT",
    SET_SNACKBAR: "SET_SNACKBAR"
  },
  actions: {
    POST_CREATE: "POST_CREATE",
    POST_UPDATE: "POST_UPDATE",
    POST_REMOVE: "POST_REMOVE",
    CHANGE_POST_CURRENT: "CHANGE_POST_CURRENT",
    SHOW_SNACKBAR: "SHOW_SNACKBAR",
    HIDE_SNACKBAR: "HIDE_SNACKBAR"
  }
};
