export const types = {
  mutations: {
    CHANGE_POST: "CHANGE_POST",
    SET_SNACKBAR: "SET_SNACKBAR",
    SET_POST_UPDATE: "SET_POST_UPDATE",
    CHANGE_POST_UPDATE: "CHANGE_POST_UPDATE",
    CLEAR_FIELDS: "CLEAR_FIELDS",
    SET_DIALOG: "SET_DIALOG"
  },
  actions: {
    POST_CREATE: "POST_CREATE",
    SHOW_DIALOG: "SHOW_DIALOG",
    HIDE_DIALOG: "HIDE_DIALOG",
    POST_UPDATE: "POST_UPDATE",
    POST_REMOVE: "POST_REMOVE",
    CHANGE_POST: "CHANGE_POST",
    SHOW_SNACKBAR: "SHOW_SNACKBAR",
    HIDE_SNACKBAR: "HIDE_SNACKBAR",
    FETCH_POST: "FETCH_POST",
    FETCH_PROFILE: "FETCH_PROFILE",
    FETCH_PROFILE_ABOUT: "FETCH_PROFILE_ABOUT",
    FETCH_PROFILE_POSTS: "FETCH_PROFILE_POSTS",
    POST_PROFILE_PHOTO: "POST_PROFILE_PHOTO",
    POST_COVER_PHOTO: "POST_COVER_PHOTO"
  }
};
