export const types = {
  mutations: {
    CHANGE_POST: "CHANGE_POST",
    SET_SNACKBAR: "SET_SNACKBAR",
    SET_POST_UPDATE: "SET_POST_UPDATE",
    CHANGE_POST_UPDATE: "CHANGE_POST_UPDATE",
    CLEAR_FIELDS: "CLEAR_FIELDS"
  },
  actions: {
    POST_CREATE: "POST_CREATE",
    POST_UPDATE: "POST_UPDATE",
    POST_REMOVE: "POST_REMOVE",
    CHANGE_POST: "CHANGE_POST",
    SHOW_SNACKBAR: "SHOW_SNACKBAR",
    HIDE_SNACKBAR: "HIDE_SNACKBAR",
    FETCH_POST: "FETCH_POST"
  }
};
